### ISSUE TITLE
Simple Access Token Protection

### ISSUE THREAD

**Issue by wurstbrot** [devsecopsmaturitymodel/metricAnalyzer#27]
Because oauth client credentials flow might not be available, a simple token is defined.

The following properties will be used:

application.properties:
`metricCA.access.token.enabled=true/false`
`metricCA.access.token.secret.path=/xyz/accesstoken.properties`

accesstoken.properties:
`metricCA.access.token.secret=abc`

`accesstoken.properties` should be included in addition to the profile-based property in order to mount it as secret via kubernetes.

**Comment by shery9** [comment]
Hello Timo, can you please add gituser "eiquanasfiya" into this repo to write.

remote: Permission to devsecopsmaturitymodel/metricAnalyzer.git denied to eiquanasfiya.
fatal: unable to access 'https://github.com/devsecopsmaturitymodel/metricAnalyzer.git/': The requested URL returned error: 403

**Comment by eiquanasfiya** [comment]
Hello Timo, can you please add gituser "eiquanasfiya" and "shery9" into this repo to write.

remote: Permission to devsecopsmaturitymodel/metricAnalyzer.git denied to eiquanasfiya.
fatal: unable to access 'https://github.com/devsecopsmaturitymodel/metricAnalyzer.git/': The requested URL returned error: 403
